server:
  command: "php psr-worker.php"

http:
  address: 127.0.0.1:8080
  middleware: [ "static" ]
  pool:
    num_workers: 4
  static:
    dir: "./static"
    forbid: []
    calculate_etag: false
    weak: false
    request:
      input: "custom-header"
    response:
      output: "output-header"  